### ISSUE TITLE
Refactor existing non-suspend fx blocks

### ISSUE THREAD

**Issue by nomisRev** [arrow-kt/arrow-core#117]
The current `fx` implementation is coupled to the JVM, and this prevents Arrow-Core from becoming MPP.

The new implementation in #112 can be adjusted to work with `@RestrictSupension`, and not be coupled to the JVM.

The new implementation should also be exposed from `arrow-core-data` on the respective `companion object`.

This needs to happen for all data types that are not marked for deprecation in #114.

 - [x] `Either`
 - [x] `Validated`
 - [ ] `NonEmptyList`
 - [x] `Eval`
 - [x] `Const`
 - [ ] `Ior`

A reference PR will be linked asap.

**Comment by aballano** [comment]
Leftover datatypes will be tackled in #171
