### ISSUE TITLE
`orNull` API to cover the deprecated `Option` API.

### ISSUE THREAD

**Issue by nomisRev** [arrow-kt/arrow-core#120]
`orNull` is a common API in Kotlin in contrast to `Option`.
If we are to deprecate `Option` as planned in #114 then we should also provide alternative APIs for the current `Option` APIs.

`Option` or `?` is used to make unsafe APIs safe, or to indicate absence/terminal operations.

 - `headOption` -> `firstOrNull` 
 - `tailOption` -> `lastOrNull`
 - `mapFilter` -> `mapNotNull`

**Comment by aballano** [comment]
There seem to be a legit usage of Option that we might need to consider https://github.com/arrow-kt/arrow-core/issues/114#issuecomment-633230552
