### ISSUE TITLE
["Request"] Fix NPE in bindWithFilter

### ISSUE THREAD

**Issue by brezinajn** [arrow-kt/arrow-core#132]
What version are you currently using?
0.10.5
What would you like to see?
`bindWithFilter` crashes when it encounters second element that satisfies the predicate.
Min. repro:
```Kotlin
val list = listOf(1,2,3,4).k()
ListK.monadFilter().fx.monadFilter {
    list.bindWithFilter { it % 2 == 0 }
}.let(::println)
```
Crashes with NPE.
```Kotlin
val list = listOf(1,2,3).k()
ListK.monadFilter().fx.monadFilter {
    list.bindWithFilter { it % 2 == 0 }
}.let(::println)
```
This works fine though.

**Comment by aballano** [comment]
Fixed, thank you a lot for the report @brezinajn!! It should be available soon in the snapshot and in the next version we release (0.11 most probably).
