### ISSUE TITLE
Figure out a name for non-suspend fx block

### ISSUE THREAD

**Issue by aballano** [arrow-kt/arrow-core#133]
Related to #117

> `fxEager`? `fxNow`? `fxJust`?

_Originally posted by @pakoito in https://github.com/arrow-kt/arrow-core/pull/124_

**Comment by pakoito** [comment]
Oh thank god please yes

**Comment by aballano** [comment]
I'm in favour of `fxEager` or `eagerFx`

**Comment by pakoito** [comment]
fxEager for discoverability

**Comment by aballano** [comment]
Seems that the [problem is solved(?)](https://github.com/arrow-kt/arrow-core/pull/160/files#diff-048837e2615e457be422388de720353fR46) 👀
