### ISSUE TITLE
Why can't I easily "bind" instead of map Validated objects

### ISSUE THREAD

**Issue by Zordid** [arrow-kt/arrow-core#16]
What version are you currently using?
0.9.0
What would you like to see?
I really, really struggle with Validated / ValidatedNel

I simply do not understand why easy things like flatMap or aka bind are not available.

I have a ValidatedNel<ErrorType, Data> variable x and another function f that takes a Data and produces a ValidatedNel<ErrorType, Data> f(Data): ValidatedNel<Error, Data>

I cannot find a way to do

x.flatMap(::f) 

What I want is easy:
if x is valid, take the data, run f(data) and return its result.
if x in invalid, just return x

What am I missing?

**Comment by nomisRev** [comment]
> We couldn't have that on Arrow directly, so having these helpers in your codebase is okay.

@pakoito  since we do not want to promote this pattern in Arrow can we close this issue?

**Comment by nomisRev** [comment]
Hey @Zordid,

This will be solved for all data types with #115 & #112! We're actively starting to work and plan this work now so you can track it there ;)
