### ISSUE TITLE
["Request"] make Option and Try be Iterable

### ISSUE THREAD

**Issue by danwallach** [arrow-kt/arrow-core#17]
_What version are you currently using?_ 0.9.0

_What would you like to see?_ Arrow's `Option` and `Try` classes implement `Iterable`

Consider the case where you're using Kotlin's `flatMap` over its lists:
`public inline fun <T, R> Iterable<T>.flatMap(transform: (T) -> Iterable<R>): List<R>`

The `transform` lambda can return any `Iterable`. It would be handy to be able to return an `Option` or `Try` in a circumstance like this, where iterating an empty option would return nothing, and iterating a non-empty option would return the contents. 

FWIW, VAVR's [Option](https://github.com/vavr-io/vavr/blob/master/vavr/src/main/java/io/vavr/control/Option.java) extends its [Value](https://github.com/vavr-io/vavr/blob/master/vavr/src/main/java/io/vavr/Value.java), which in turn extends Java's `Iterable`, so VAVR's `flatMap` can accept `Option` instances.

VAVR's `Try` class is also `Iterable`, behaving much the same as `Option`, returning one or zero values when iterated.

**Comment by nomisRev** [comment]
Closing this ticket. There seems to be a consensus to not include this in Arrow.

Additionally Kotlin has utilities to do this ad-hoc based on structurally implementing `operator`for `Iterator`. https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-iterator/
