### ISSUE TITLE
Nel<T> is not actually a List<T>. Should this be changed?

### ISSUE THREAD

**Issue by acanthite** [arrow-kt/arrow-core#190]
**What version are you currently using?**
0.10.5

**What would you like to see?**
I'd like to see Nel actually implementing `List<T>`. It annoys me pretty often that I have to use the `all` property and cannot pass Nel to where a list is needed.
Kotlin has great starting point for making custom list implementations, it's the [ `AbstractList<T>` class](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-abstract-list/). Was this considered during implementation? 
I always feel a bit distracted that arrow's Nel uses twice the amount of memory it actually needs: one for the `head` & `rest` and exactly the same amount for the `all`.
Here what it can look like, if we implemented it via `AbstractList`:
```kotlin
class NonEmptyList<T> (val first: T, val rest: List<T>): AbstractList<T>() {
	override val size = 1 + rest.size

	override operator fun get(index: Int): T {
		if (index < 0 || index >= size) throw IndexOutOfBoundsException(index)
		return if (index == 0) first else rest[index - 1]
	}
}
```
It is just as simple as that. And we get alot of functionality for free:
- Reduced memory consumption (compared to the current implementation of Nel),
- equals/hashCode
- toString()
- Iterator
- Indexing
Just about everything that `List<T>` has. And what's more important: the class implements `List<T>` now (and thus, `Collection<T>`, `Iterable<T>`) which allows:
- use it in place where one of those needed
- use all the hell of extension functions provided by the kotlin standard lib.

Of course we have all these features via `all` property. But why not having it on Nel directly, if it is that simple?

**Comment by 1Jajen1** [comment]
Well as long as there is no way to unsafely construct a `Nel` using `AbstractList` the actual implementation of `Nel` does not matter.
If this does not lead to unsafe uses then it does sound like a good idea!

We could also define it as `class Nel<T>(val backingList: List<T>): AbstractList<T>()` and defer all list operations to the backing list. Again as long as we don't provide unsafe constructor methods everything goes ^^

**Comment by acanthite** [comment]
@1Jajen1 Backing list is fine too. It could be even written with delegates, so that the `AbstractList<T>` isn't required at all:
```kotlin
class Nel<T> private constructor (val backingList: List<T>): List<T> by backingList;
```
Plus in this case, we need to keep the constructor private, and allow creation only via functions (of companion object, just like it is now)
