### ISSUE TITLE
["Request"] New module with arrow-integrations arrow-core retrofit integration

### ISSUE THREAD

**Issue by nomisRev** [arrow-kt/arrow-core#209]
We should promote the integration for `Either` here, since this now offers a perfect fit with `Arrow-Core` & `Arrow Fx Coroutines` as discussed here.

https://github.com/arrow-kt/arrow-core/pull/195#issuecomment-672893490

**Comment by rachelcarmena** [comment]
Please @nomisRev , could you specify which content from `arrow-integrations` should be moved to this repository? I'm thinking about keeping the Git history from that content when it's added here.

**Comment by rachelcarmena** [comment]
Done!! `arrow-core-retrofit` already exists with the promoted features and keeping the Git history. Besides [this pull request removes it from `arrow-integrations`](https://github.com/arrow-kt/arrow-integrations/pull/39)

**Comment by rachelcarmena** [comment]
It has been promoted directly on `master` branch to keep the Git history and to be moved to a new module with the necessary configuration.
