### ISSUE TITLE
["Request"] Remove Try examples from documentation

### ISSUE THREAD

**Issue by kylegoetz** [arrow-kt/arrow-core#26]
What version are you currently using? 0.10

What would you like to see?

The documentation includes `Try` examples. Since `Try` is deprecated, these examples should be removed (or transitioned to `Either` examples) to prevent confusion.

**Comment by aballano** [comment]
Hi, I've seen there's this PR opened in the old monorepo https://github.com/arrow-kt/arrow/pull/1979 @kylegoetz would you like/be able to continue it? Otherwise we would like to pick it in order to have it ready for the 0.10.x release. If you need any help migrating it ping us or @rachelcarmena :)

**Comment by kylegoetz** [comment]
@aballano Yes, I do need help. I'm not aware of any repository besides this one. This is the repo I cloned and changed. Also, from what I recall, my changes stretch across many of the modules, not just one. So isn't that the right one to have my PR for?

**Comment by kylegoetz** [comment]
Actually I guess I notice now that this is `arrow-kt/arrow-core` and not `arrow-k/tarrow`. So I need to do a PR for this with my changes.

That being said, IIRC the other PR is more than just `arrow-core` changes. I think other modules (like the optics, fx, mtl, etc.) might have also had Try stuff I removed.

**Comment by aballano** [comment]
@kylegoetz Indeed the process would be looking at the files changed and just porting the change to the respective repo. I can do that for you tomorrow and we can keep sync in Slack if needed :)

**Comment by kylegoetz** [comment]
@aballano Cool beans. I'll keep slack open. FYI this PR and #1915 (moving "nuclear" examples to "cooking" examples) are kind of tied up a bit in a confusing way, and I'm not sure of the status of both.

Essentially, the timeline was:

1. I replace nuclear with cooking (including Try examples)
2. PR for that #1915
3. remove Try stuff across modules
4. this PR

The two PRs overlap in the Try nuclear example. Since the first wasn't accepted/merged before I did the second, I'm not sure how this overlap is affected right now in the actual Arrow repo (i.e., whether there is a Try nuclear, whether the cooking has Try or not, etc.).

**Comment by danimontoya** [comment]
Hi @kylegoetz your work has been moved across all new repos, in case you would like to have a look.. you can find it here, thanks!
- https://github.com/arrow-kt/arrow-core/pull/50
- https://github.com/arrow-kt/arrow-fx/pull/69
- https://github.com/arrow-kt/arrow-optics/pull/22
- https://github.com/arrow-kt/arrow-incubator/pull/48
- https://github.com/arrow-kt/arrow-examples/pull/1
- https://github.com/arrow-kt/arrow-site/pull/12
