### ISSUE TITLE
Add `flatten` to `MonadFilter`

### ISSUE THREAD

**Issue by nomisRev** [arrow-kt/arrow-core#8]
Add following derived method to `MonadFilter` as requested originally in the tweet mentioned in arrow-kt/arrow#1501.

```
fun <A> Kind<F, Option<A>>.flatten(): Kind<F, A> =
   filterMap(::identity)
```

**Comment by danimontoya** [comment]
I was checking this issue.. so two things I found out:
- flatten is already derived from `Monad`.
- `fun <A> Kind<F, Option<A>>.flatten(): Kind<F, A>` can be added but we might need to change the name.

How should we proceed with this? @nomisRev

**Comment by nomisRev** [comment]
Can we overload in `MonadFilter` based on the signature of the receiver and overload it with `@JvmName("flattenOption")` ?

**Comment by danimontoya** [comment]
yes, indeed.. flatten is in Monad is like that: `Kind<F, Kind<F, A>>.flatten`
Yeah, I thought of that.. but seems like _`@JvmName("flattenOption")` annotation is not applicable to this declaration_

**Comment by nomisRev** [comment]
I'm sorry @danimontoya seems like it's already implemented in [FunctorFilter](https://github.com/arrow-kt/arrow-core/blob/master/arrow-core-data/src/main/kotlin/arrow/typeclasses/FunctorFilter.kt#L24)
