### ISSUE TITLE
Error handling code samples don't compile

### ISSUE THREAD

**Issue by tomvandenberge** [arrow-kt/arrow-core#95]
Embarrassingly, the [`Option` code samples](https://arrow-kt.io/docs/0.10/patterns/error_handling/#option) don't compile.

The import of `arrow.core.extensions.option.monad.binding` can't be resolved. Apparently `fx` is in there, because it can't be resolved. The same goes for `bind()`. IntelliJ doesn't come up with suggestions on where to import `fx` from.

**Comment by rachelcarmena** [comment]
Created #96 to fix them. Thanks @JorgeCastilloPrz :raised_hands:
