### ISSUE TITLE
Some(null) sucks !

### ISSUE THREAD

**Issue by moeKiwiSAMA** [arrow-kt/arrow-core#97]
In Scala, Option(null) = None:
```scala
scala> Option(null)
res0: Option[Null] = None
```

But in arrow-kt, Option(null) = Some(null):
```kotlin
println(Option(null))
=> Some(null)
```

When interacting with JAVA, some libraries will return a null rather than an exception, which causes Some(null) appeared and leads `when expression` into a failure.
```kotlin
when(anOption) {
    is Some<T> -> anOption.t // is also nullable
    is None -> "Nothing" // is unreachable
}
```

Hoping arrow-kt could work like Scala, and makes `Some(null) = None` if possible.

**Comment by pakoito** [comment]
FAKE NEWS

**Comment by pakoito** [comment]
Now seriously, use one of the other constructors that evaluates the element inside. `toOption()` or `fromNullable()`
