### ISSUE TITLE
Either.cond parameter order mismatch

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow-core#98]
All of our APIs have errors on the left...except for that one.

https://github.com/arrow-kt/arrow-core/blob/master/arrow-core-data/src/main/kotlin/arrow/core/Either.kt#L866

As seen in https://youtu.be/tN_k1W1hEhA?t=7094

**Comment by sierisimo** [comment]
I want to help on this.

My first question is: how can we fix it without breaking projects currently using the current version?

I was thinking maybe add: `condl(condition, leftFun, rightFun)` and mark the current `cond` with `@Deprecated(…)`

And maybe after two releases, return the `condl` to be named just `cond`. It sounds annoying for the developer but also feels like a safe way to just fix this without breaking anything.

**Comment by pakoito** [comment]
Let's come up with a new name altogether IMO. `invariant` or something similar.

**Comment by sierisimo** [comment]
I like `invariant`. 

I was searching for _synonyms_ of conditional but only feel like `even` was the closest to what the intention of the function is.

Maybe… just maybe, adding `even` now and later move `cond` to `odd`. too crazy? Ok, `invariant` looks good.

**Comment by pakoito** [comment]
hiosdra in slack suggested `conditionally`

**Comment by pakoito** [comment]
Let's see what twitter thinks

https://twitter.com/pacoworks/status/1255441621325361152

**Comment by sierisimo** [comment]
I like `conditionally` and seems like twitter too. Lot of good ideas in that thread

**Comment by Hiosdra** [comment]
❤️
